-- Library Management System - Phase 1 database schema
-- PostgreSQL 14+ recommended.
-- This script creates only the database schema and representative seed data.

BEGIN;

-- Re-running the script starts from a clean schema for local testing.
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users cover both staff and library patrons. Passwords are represented by a
-- hash column; the application must provide the hashing and authentication layer.
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'patron',
    phone VARCHAR(30),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_role_check CHECK (role IN ('librarian', 'patron'))
);

-- Categories are independent lookup records. A book must belong to exactly one
-- category, enforced by the non-null foreign key on books.category_id.
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- The catalog stores the current availability state of each physical/catalog
-- item. Historical checkout state belongs in issues, not in this table.
CREATE TABLE books (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    isbn VARCHAR(17) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(200) NOT NULL,
    publisher VARCHAR(200),
    publication_year INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT books_category_fk FOREIGN KEY (category_id)
        REFERENCES categories (category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT books_publication_year_check CHECK (
        publication_year IS NULL OR publication_year BETWEEN 1000 AND 2100
    ),
    CONSTRAINT books_status_check CHECK (status IN ('available', 'issued', 'reserved'))
);

-- Each row represents one checkout event. The unique issue_id relationship used
-- by returns allows at most one return record for a checkout.
CREATE TABLE issues (
    issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT issues_user_fk FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT issues_book_fk FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT issues_date_order_check CHECK (due_at >= issued_at),
    CONSTRAINT issues_returned_at_check CHECK (returned_at IS NULL OR returned_at >= issued_at),
    CONSTRAINT issues_status_check CHECK (status IN ('pending', 'completed', 'overdue'))
);

-- A return is tied to one and only one issue. A separate table preserves return
-- details without overwriting the original checkout record.
CREATE TABLE returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL UNIQUE,
    returned_by_user_id BIGINT NOT NULL,
    returned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    condition_notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT returns_issue_fk FOREIGN KEY (issue_id)
        REFERENCES issues (issue_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT returns_user_fk FOREIGN KEY (returned_by_user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT returns_status_check CHECK (status IN ('pending', 'completed', 'overdue'))
);

-- Reservations are independent requests and may be queued by multiple users
-- for the same book. The partial unique index below prevents duplicate active
-- reservations by the same user for the same book.
CREATE TABLE reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reservations_user_fk FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT reservations_book_fk FOREIGN KEY (book_id)
        REFERENCES books (book_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT reservations_expiry_check CHECK (expires_at IS NULL OR expires_at >= reserved_at),
    CONSTRAINT reservations_status_check CHECK (status IN ('pending', 'fulfilled', 'cancelled', 'expired'))
);

-- Foreign-key indexes support joins and the most common user/book lookups.
CREATE INDEX idx_books_category_id ON books (category_id);
CREATE INDEX idx_books_status ON books (status);
CREATE INDEX idx_issues_user_id ON issues (user_id);
CREATE INDEX idx_issues_book_id ON issues (book_id);
CREATE INDEX idx_issues_status_due_at ON issues (status, due_at);
CREATE INDEX idx_returns_returned_by_user_id ON returns (returned_by_user_id);
CREATE INDEX idx_reservations_user_id ON reservations (user_id);
CREATE INDEX idx_reservations_book_id_status ON reservations (book_id, status);
CREATE UNIQUE INDEX uq_active_reservation_user_book
    ON reservations (user_id, book_id)
    WHERE status IN ('pending', 'fulfilled');

-- Five users: both supported roles are represented.
INSERT INTO users (user_id, full_name, email, password_hash, role, phone) VALUES
    (1, 'Amina Patel', 'amina.patel@example.com', 'hash_demo_001', 'librarian', '+1-555-0101'),
    (2, 'Jon Bell', 'jon.bell@example.com', 'hash_demo_002', 'librarian', '+1-555-0102'),
    (3, 'Maya Chen', 'maya.chen@example.com', 'hash_demo_003', 'patron', '+1-555-0103'),
    (4, 'Luis Gomez', 'luis.gomez@example.com', 'hash_demo_004', 'patron', '+1-555-0104'),
    (5, 'Nora Williams', 'nora.williams@example.com', 'hash_demo_005', 'patron', '+1-555-0105');

-- Five categories provide lookup values for the catalog sample.
INSERT INTO categories (category_id, name, description) VALUES
    (1, 'Fiction', 'Novels and short stories'),
    (2, 'Science', 'Scientific and technical works'),
    (3, 'History', 'Historical studies and primary sources'),
    (4, 'Technology', 'Computing and information technology'),
    (5, 'Biography', 'Lives and memoirs');

-- Five catalog records cover all book statuses.
INSERT INTO books (book_id, category_id, isbn, title, author, publisher, publication_year, status) VALUES
    (1, 1, '9780140449136', 'The Odyssey', 'Homer', 'Penguin Classics', NULL, 'available'),
    (2, 2, '9780262033848', 'Introduction to Algorithms', 'Thomas H. Cormen', 'MIT Press', 2022, 'issued'),
    (3, 3, '9780199537822', 'A History of the World', 'J. M. Roberts', 'Oxford University Press', 1997, 'reserved'),
    (4, 4, '9780132350884', 'Clean Code', 'Robert C. Martin', 'Prentice Hall', 2008, 'available'),
    (5, 5, '9781501173219', 'Leonardo da Vinci', 'Walter Isaacson', 'Simon & Schuster', 2017, 'issued');

-- Five checkout events; statuses demonstrate pending, completed, and overdue.
INSERT INTO issues (issue_id, user_id, book_id, issued_at, due_at, returned_at, status) VALUES
    (1, 3, 2, '2026-09-01 10:00:00+00', '2026-09-15 10:00:00+00', NULL, 'overdue'),
    (2, 4, 5, '2026-09-10 14:00:00+00', '2026-09-24 14:00:00+00', NULL, 'pending'),
    (3, 5, 1, '2026-08-01 09:00:00+00', '2026-08-15 09:00:00+00', '2026-08-14 16:00:00+00', 'completed'),
    (4, 3, 4, '2026-07-01 11:30:00+00', '2026-07-15 11:30:00+00', '2026-07-14 12:00:00+00', 'completed'),
    (5, 4, 3, '2026-06-01 13:00:00+00', '2026-06-15 13:00:00+00', '2026-06-20 13:00:00+00', 'completed');

-- Five return records, one per completed checkout in this sample.
INSERT INTO returns (return_id, issue_id, returned_by_user_id, returned_at, condition_notes, status) VALUES
    (1, 3, 5, '2026-08-14 16:00:00+00', 'Good condition', 'completed'),
    (2, 4, 3, '2026-07-14 12:00:00+00', 'Minor cover wear', 'completed'),
    (3, 5, 4, '2026-06-20 13:00:00+00', 'Good condition', 'completed'),
    (4, 1, 3, '2026-09-21 09:00:00+00', 'Returned after due date', 'overdue'),
    (5, 2, 4, '2026-09-21 10:00:00+00', 'Good condition', 'pending');

-- Five reservation records demonstrate pending, fulfilled, cancelled, and expired.
INSERT INTO reservations (reservation_id, user_id, book_id, reserved_at, expires_at, status) VALUES
    (1, 5, 3, '2026-09-20 08:00:00+00', '2026-09-27 08:00:00+00', 'pending'),
    (2, 3, 2, '2026-09-05 12:00:00+00', '2026-09-12 12:00:00+00', 'fulfilled'),
    (3, 4, 4, '2026-08-20 15:00:00+00', '2026-08-27 15:00:00+00', 'cancelled'),
    (4, 5, 5, '2026-08-01 10:00:00+00', '2026-08-08 10:00:00+00', 'expired'),
    (5, 3, 1, '2026-09-18 09:30:00+00', '2026-09-25 09:30:00+00', 'pending');

-- Keep identity sequences ahead of the explicit seed IDs so future inserts do
-- not collide with the sample data.
SELECT setval(pg_get_serial_sequence('users', 'user_id'), 5, TRUE);
SELECT setval(pg_get_serial_sequence('categories', 'category_id'), 5, TRUE);
SELECT setval(pg_get_serial_sequence('books', 'book_id'), 5, TRUE);
SELECT setval(pg_get_serial_sequence('issues', 'issue_id'), 5, TRUE);
SELECT setval(pg_get_serial_sequence('returns', 'return_id'), 5, TRUE);
SELECT setval(pg_get_serial_sequence('reservations', 'reservation_id'), 5, TRUE);

COMMIT;